### ISSUE TITLE
Figure 7 optimized vs. default for the 1B model.

### ISSUE THREAD

**Issue by sia-cerebras** [yegcjs/mixinglaws#2]
Hi, First thanks for publishing your code.

I'm looking at Fig. 7 and would understand which one of the extrapolated red points is for the default mixture and which is for the optimized mixture. 
I tried to plot each of the extrapolated points differently by changing 
```ax.scatter(eval_predictions, eval_observations, color="red", label="extrapolation")```
to
```ax.scatter(eval_predictions, eval_observations, color=["red", "green"], label="extrapolation")```.

I'm getting the following plot:
![image](https://github.com/yegcjs/mixinglaws/assets/101586439/7e24e275-4129-453a-8a2b-4722284f1ba5)
Could you tell me (1) if this is right and (2) if yes, which color is optimized and which is the default?

Thank you

**Comment by yegcjs** [comment]
Thanks for adding this to make the plot clearer!
The green dots are the optimized ones.
