### ISSUE TITLE
how do we calculate the optimal mixing ratio

### ISSUE THREAD

**Issue by waltonfuture** [yegcjs/mixinglaws#3]
![image](https://github.com/yegcjs/mixinglaws/assets/98318797/b7a99d28-05c3-4218-8163-192b2712d173)

Hello authors, I want to ask a simple question. In this function in the image, how do we calculate the optimal mixing ratio (that is, $r_1$ to $r_M$)?

**Comment by yegcjs** [comment]
We just grid search the proportions to find the smallest one.
Please let me know if anyone can figure out or have some insight on a closed-form solution :)
