### ISSUE TITLE
power law的对应关系

### ISSUE THREAD

**Issue by yangsp5** [yegcjs/mixinglaws#4]
`utils.py`里面的power_law是计算逻辑如下，但是论文中的公式M4并没有x，这里的对应关系是什么呢？
* 代码实现
```{python}
def power_law_(x, param):
    log_c, log_k, alpha = param
    return torch.exp(log_c) + torch.exp(alpha * (log_k - torch.log(x)))
```
* 公式
$L_i(\boldsymbol{r}) = c_i + k_i \exp \left(    \sum_{j=1}^{M} t_{ij} r_j     \right)$

**Comment by yegcjs** [comment]
您好，power law用于计算scaling laws of training steps / model sizes，M4公式对应utils中的mixture_law_
